# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dr. rer. nat. Joschua Dilly
title: Postdoc. at CERN
# email: mail at websitename
website: jdilly.de

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: joschd
stackoverflow_username: "5609590"
linkedin_username: joschua-dilly-904a5a200
orcid_username: 0000-0001-7864-5448

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-book
  url: https://scholar.google.ch/citations?user=AxIC3M4AAAAJ


# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)


# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi and thank you for stopping by!

  Let me use this opportunity to present myself.

  Being initiated to hard puzzles at an early age through MYST by my dad, I developed a passion for figuring out how things work.
  I am now a physicist, because I like to describe them with a clear and precise language
  and a Python programmer, because I also like contradictions.

  In the last years I dived into the amazing field of accelerator physics,
  while at the same time developing my coding skills - from _"physicist"_
  to _"readable"_ and sometimes even _"nicely documented"_ - thanks to the help, inspiration and criticism from very talented colleagues.

  Check out my [Google Scholar](https://scholar.google.ch/citations?user=AxIC3M4AAAAJ) for the science part
  and my [Github](https://github.com/JoschD) for the codes.


content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CERN
        # quote: >
        # Making sure the LHC goes brrrrrrr correctly.
        sub_title: Postdoctoral Researcher (Fellow)
        caption: Mar 2023 - Feb 2026
        quote: >
          European Organization for Nuclear Research, Geneva, CH
        description: |
            Research in accelerator physics, especially in the measurement and correction of LHC and HL-LHC beam optics.<br>
            Simulation and data analysis campaigns.<br>
            Software maintenance, development, refactoring and testing of analysis tools and graphical user interfaces in Python and Java.

      - layout: left
        title: CERN
        # quote: >
        # Making sure the LHC goes brrrrrrr correctly.
        sub_title: PhD Student
        caption: Sep 2019 - Nov 2022
        quote: >
          European Organization for Nuclear Research, Geneva, CH
        description: |
          Thesis Title: [_"Corrections of high-order nonlinearities in the LHC and High Luminosity LHC beam optics"_](https://repository.cern/records/whbes-msj47).<br>
          Under the caring supervision of [Dr. Rogelio Tomás-García](http://rtomas.web.cern.ch/rtomas/).

      - layout: left
        title: CERN
        quote: >
          European Organization for Nuclear Research, Geneva, CH
        sub_title: Researcher (International Volunteer)
        caption: Sep 2017 - Sep 2019
        description: |
          Research in accelerator physics, especially in the measurement and correction of beam optics.<br>
          Simulation and data analysis campaigns.<br>
          Software development of analysis tools and graphical user interfaces in Python and Java.

      - layout: left
        title: HHI
        quote: >
          Fraunhofer Heinrich Hertz Institute, Berlin, DE
        sub_title: Research Assistant
        caption: Aug 2015 - Dec 2015
        description: |
          Development of a Python-based interface between VPI Photonic Components and MATLAB.

      - layout: left
        title: HHI
        quote: >
          Fraunhofer Heinrich Hertz Institute, Berlin, DE
        sub_title: Student Research Assistant
        caption: Dec 2013 - Aug 2015
        description: |
          Masters Thesis: [_Quality-of-transmission estimation in physical impairment-aware flexible optical networks_](https://arxiv.org/abs/2012.06477). <br>
          Digital Signal Processing and Performance Monitoring in Flexible Optical Networks: MATLAB/VPI Photonic Components simulations. <br>
          DSP-Toolbox development.

      - layout: left
        title:  BAM
        quote: >
          Bundesanstalt für Materialforschung und -prüfung, Berlin, DE
        sub_title: Intern
        caption: Mar 2013 - May 2013
        description: |
          Acoustic wave propagation in waveguides: SB-FEM simulations in MATLAB continued
          [(Acknowledgement)](https://www.sciencedirect.com/science/article/pii/S0022460X12000764).

      - layout: left
        title:  BAM
        quote: >
          Bundesanstalt für Materialforschung und -prüfung, Berlin, DE
        sub_title: Intern
        caption: Apr 2012 - Jul 2012
        description: |
          Acoustic wave propagation in waveguides: SB-FEM simulations in MATLAB.

      - layout: left
        title: ABB
        quote: >
          ABB Switzerland Ltd. (ABB Schweiz AG), Baden Dättwil, CH
        sub_title: Intern
        caption: Sep 2011 - Dec 2011
        description: |
          Implementation of surface plasma interaction models as boundary conditions for electrical
          current calculations: FEM Simulation in MATLAB
          [(Reference)](https://ui.adsabs.harvard.edu/abs/2013APS..GECCT1011H/abstract).


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Humboldt University of Berlin
        caption: 2019 - Present
        sub_title: PhD
        # quote: >
        #   "The most dangerous worldview is the worldview of those who have never viewed the world." - Alexander von Humboldt
        description: | # this will include new lines to allow paragraphs
          I am currently writing my PhD Thesis
          _"Corrections of high-order nonlinearities in the LHC and High Luminosity LHC beam optics"_.

          Expertedly supervised by [Prof. Dr. Andreas Jankowiak](https://www.helmholtz-berlin.de/pubbin/vkart.pl?v=adzou),
          who made my start at `CERN` already much easier by providing me with his lecture materials beforehand.

      - layout: left
        title: Technical University Berlin
        caption: 2012 - 2016
        sub_title: Master's degree in Physics
        # quote: >
        #  “If you thought that science was certain - well, that is just an error on your part.”
        #   ― Richard P. Feynman
        description: |
          With the background of my bachelor's studies, the fundamental physics course at the TU-Berlin were the logical choice on the way to obtain a master's degree.
          After a short intermezzo as an intern at `ABB` and `BAM` to get an insight of a researcher's life,
          I did two semesters of lectures at the TU, before working full-time on my thesis at the `HHI`
          about [_"Quality-of-transmission estimation in physical impairment-aware flexible optical networks"_](https://arxiv.org/abs/2012.06477).

      - layout: left
        title: University of Basel
        caption: 2008 - 2011
        sub_title: Bachelor's degree in Computational Physics
        # quote: >
        #   “I would rather have questions that can't be answered than answers that can't be questioned.”
        #   ― Richard P. Feynman
        description: | # this will include new lines to allow paragraphs
          I chose the studies of computational physics, as the curriculum required to attend the basic courses
          of the other natural sciences as well, and I did not yet feel finished with biology and chemistry.
          In addition, all laboratory work was replaced by lectures in simulations and optimization theory,
          and the fundamental lectures of programming and computer science were mandatory.
          It was indeed an ideal curriculum to start a career in modern natural sciences, in which the use of computers becomes even more prevalent than laboratories.

          Outside of the core curriculum, I enjoyed the philosophic-astronomic-meta-physical lectures of
          [Prof. Roland Buser](https://de.wikipedia.org/wiki/Roland_Buser) a lot, and I hope that they are still a thing.


  - title: Skills
    layout: list
    content:
      - layout: left
        title:  Accelerator Physics
        description: |
          I started with accelerator physics in 2017 at my first Job at `CERN`.
          In the [**Optics Measurements and Correction Team**](https://pylhc.github.io/),
          we are developing new methods to find errors in the LHC beam optics (read: magnetic fields)
          and are finding new ways to correct them efficiently.


      - layout: left
        title: Computational Physics
        description: |
          I have a passion for working at the intersection between reality and simulation,
          enjoying coding much more than setting up experiments and finding new solutions to problems by putting them into algorithms.
          During my bachelor's, I was introduced to different methods of optimization and ways to simplify complex object interactions without loosing the important features.


      - layout: left
        title: Mathematical Optimization / Numerical Analysis
        description: |
          As mentioned above, numerical analysis and mathematical optimization were big parts of my bachelor's education and the skills
          taught there have been constant companions ever since and  proven to be very useful in the life of a computational physicist.

      - layout: left
        title: Python
        description: |
          Most of my coding is done in python, mainly for its simplicity and because speed has been rarely the most important factor in first prototyping calculations.
          Thanks to the interfaces provided in the language, performance optimization of the code is still possible if necessary.
          I am very comfortable in it and - in my opinion - know how to write pythonic, readable, well documented code.
          If there is time.
          One should also not underestimate the amount of problems solvable by sprinkling some regular expressions here and there.

          I am especially versed in pandas for data analysis, numpy and scipy.

      - layout: left
        title: Java
        description: |
          The language I learned in university (apart from Fortran, which I will not mention here, so no one contacts me to write some Fortran) and still use sometimes.
          At CERN, the GUI is written in Java, to which I have made multiple extensions and fixes.
          I find it very clunky though, and it is not my preferred language.

      - layout: left
        title: MATLAB
        description: |
          MATLAB was my main programming language during university as well as during the internships at
          `ABB`, `BAM`  and during my master's at `HHI`. Only when starting at `CERN` it was replaced by Python as my go-to programming language.

      - layout: left
        title: C++
        description: |
          While I have programmed in C++ for some courses in university, I have not properly used it for many years.
          I am sure that the knowledge would come back quickly if needed.

      - layout: left
        title: Fortran
        description: |
          The same as for C++ goes for Fortran: While being the original language that I have been taught computational physics in, I have luckily not had to use it for writing in years.
          I did however stumble during my career into the odd 1000 lines of Fortran legacy code, just waiting to be understood and then rewritten in 10 lines of Python.

      - layout: left
        title: LaTeX
        description: |
          If the only available templates are _.doc_ or _.ppt_ for me to use, chances are there will be soon a
          [LaTeX Template](https://pylhc.github.io/resources/templates) for it as well.
          Happy to share! (The Excel tables are pandas now. See the python section.)

      - layout: left
        title: English
        description: |
          Everyday language. All my devices are in English so my brain does not have to switch (and possibly break).

      - layout: left
        title:  German
        description: |
          My native tongue, but sometimes I think my English is better.

      - layout: left
        title: French
        description: |
          A1 on paper, but rarely utilized. Just enough to get buy while shopping.
          Happy for opportunities to practice more!

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Plofeld
        sub_title: A python plotting library for physical fields.
        # link: https://github.com/JoschD/plofeld
        # link_text: Plofeld on Github
        additional_links:
          - title: Plofeld on Github
            icon: fab fa-github
            url: https://github.com/JoschD/plofeld
          - title: Plofeld on PyPi
            icon: fas fa-cubes
            url: https://pypi.org/project/plofeld/
          - title: Documentation of Plofeld
            icon: fas fa-book
            url: https://joschd.github.io/plofeld
        description: |
          I wanted a picture of a dodecapole.
          Sadly, none of the pictures I found were to my liking.
          Instead of drawing a dodecapole I thought it would be more fun to write some code to plot all kinds of fields.<br>
          And here we are ...

      - layout: top-middle
        title: cpymad-lhc
        sub_title: Helper Functions for cpymad to run LHC optics.
        additional_links:
          - title: cpymad-lhc on Github
            icon: fab fa-github
            url: https://github.com/JoschD/cpymad_lhc
          - title: cpymad-lhc on PyPi
            icon: fas fa-cubes
            url: https://pypi.org/project/cpymad-lhc/
          - title: Documentation of cpymad-lhc
            icon: fas fa-book
            url: https://joschd.github.io/cpymad_lhc
        description: |
          A lot of accelerator optics simulations involve the use of MAD-X.
          As I am not very happy with the language provided by MAD-X,
          as are many others, I am using the pythonic approach thanks to the amazing
          [cpymad wrapper](https://github.com/hibtc/cpymad).
          In this repo I collected a lot of functions, which are of great use to run
          cpymad simulations for the LHC and HL-LHC.

          I hope they can, if not used directly, at least provide some inspiration how to
          overcome the limitations of MAD-X in a pythonic way!

      - layout: top-middle
        title: pylhc-submitter
        sub_title: Utility HTCondor Submitter for Parametrized Studies.
        additional_links:
          - title: pylhc-submitter on Github
            icon: fab fa-github
            url: https://github.com/pylhc/submitter
          - title: pylhc-submitter on PyPi
            icon: fas fa-cubes
            url: https://pypi.org/project/pylhc-submitter/
          - title: Documentation of the pylhc-submitter
            icon: fas fa-book
            url: https://pylhc.github.io/submitter
        description: |
          This package contains scripts to simplify the creation,
          parametrization and submission of simulation jobs to HTCondor clusters.

          I contributed to the [job_submitter](https://github.com/pylhc/submitter/blob/master/pylhc_submitter/job_submitter.py) and
          [AutoSix](https://github.com/pylhc/submitter/blob/master/pylhc_submitter/autosix.py),
          the latter being a prime example of my 2021 coding style.

      - layout: top-middle
        title: optics-functions
        sub_title: Calculate various beam optics functions from TFS-Dataframes.
        additional_links:
          - title: optics-functions on Github
            icon: fab fa-github
            url: https://github.com/pylhc/optics_functions
          - title: optics-functions on PyPi
            icon: fas fa-cubes
            url: https://pypi.org/project/optics-functions/
          - title: Documentation of the optics-functions
            icon: fas fa-book
            url: https://pylhc.github.io/optics_functions
        description: |
          This package provides functions to calculate various optics parameters from MAD-X TWISS outputs.

      - layout: top-middle
        title: omc3
        sub_title: Python 3 codes for beam optics measurements and corrections in circular particle accelerators.
        additional_links:
          - title: omc3 on Github
            icon: fab fa-github
            url: https://github.com/pylhc/omc3
          - title: omc3 on PyPi
            icon: fas fa-cubes
            url: https://pypi.org/project/omc3/
          - title: Documentation of omc3
            icon: fas fa-book
            url: https://pylhc.github.io/omc3
        description: |
          This is the python-tool package of the Optics Measurements and Corrections team (OMC) at CERN.

          Most of the codes are generic and not limited to CERN accelerators, and the package can easily be used for your
          favourite circular accelerator.

      - layout: top-middle
        title: PyLHC
        sub_title: Additional tools for particle accelerator data analysis and machine information.
        additional_links:
          - title: PyLHC on Github
            icon: fab fa-github
            url: https://github.com/pylhc/pylhc
          - title: PyLHC on PyPi
            icon: fas fa-cubes
            url: https://pypi.org/project/pylhc/
          - title: Documentation of pylhc
            icon: fas fa-book
            url: https://pylhc.github.io/pylhc
        description: |
          This package provides tools for particle accelerator physics complementing the optics measurement analysis tools of the omc3 package.
          It is a collection of useful scripts for the Optics Measurements and Corrections team at CERN,
          with functionality for data analysis, corrections calculation, simulations management and machine information extraction.

          My major contribution is the
          [IR NonLinear RDT Correction](https://github.com/pylhc/PyLHC/blob/master/pylhc/irnl_rdt_correction.py),
          yet the [Machine Settings Info](https://github.com/pylhc/PyLHC/blob/master/pylhc/machine_settings_info.py)
          was also implemented by me and
          the [Forced DA Analysis](https://github.com/pylhc/PyLHC/blob/master/pylhc/forced_da_analysis.py) contains
          a lot of my handwriting.

  - title: Other things I do
    layout: list
    content:
      - layout: right
        title: <img src="/images/via-ferrata.jpg" width="80%"">
        description: | # this will include new lines to allow paragraphs
          I try not to live too far away from hills and mountains throughout my life, as my sportive hobbies include
          - mountain biking
          - climbing
          - bouldering
          - via ferrata
          - skiing/snowboarding.

          On rainy days however, you will find me on my couch gaming, watching [YouTube Videos about Space Time](https://www.youtube.com/channel/UC7_gcs09iThXybpVgjHZ_7g),
          reading a fantasy or sci-fi book or jumping around within VR slaying virtual boxes.


# Footer
footer_show_references: true
references_title: Created with the <a href="https://github.com/sproogen/modern-resume-theme" target="_blank">Sproogen Modern Resume Theme</a>

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
